---
engines:
  fixme:
    enabled: true
  eslint:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      config: /actionlist/.eslintrc.json
      languages:
        - javascript
ratings:
  paths: []
exclude_paths: []
