---
engines:
  fixme:
    enabled: true
  eslint:
    enabled: false
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      config: /actionlist/.eslintrc
      languages:
        - javascript
ratings:
  paths: []
exclude_paths:
  - "actionlist/.eslintrc.json"
